### ISSUE TITLE
DynamicFields management: improve filter

### ISSUE THREAD

**Issue by ggrein** [znuny/znuny-feature-requests#60] opened 2024-04-29 12:39 UTC
The filter for DynamicFields only works for the currently displayed page listing DynamicFields. 
If you have more than one pages of DynamicFields you need to repeat the filter action on every page.

Filter criteria should either work for the whole set of Dynamic Fields or there should be an option allowing you to decide filtering only on current page or on all pages.

**Comment by rkaldung** [comment] 2024-04-30 16:31
@ggrein Most of the filter in the admin area only filter items that are shown on the current page. As a workaround you can configure the system configuration `PreferencesGroups###DynamicFieldsOverviewPageShown`. Just add 100 => 100 or 500 => 500 to the data section. Then go to AdminDynamicFields and select the new entry. All fields should be visible on the first page and the filter should work as you expect.

**Comment by jtrumm** [comment] 2024-07-04 19:10
I fully agree that the quick filters should work across all pages/all records. The same feature has been requested in #27. Maybe the 2 requests can be linked together? Anyway, the suggested workaround is working fine on our end.

**Comment by rkaldung** [comment] 2024-07-11 05:40
Duplicate of #27

**Closed as completed by rkaldung** 2024-07-11 05:40 UTC
